spring:
  r2dbc:
    url: r2dbc:mysql://13.214.234.176:3306/pos_yashoda_server
    username: dev
    password: dsj4dev
  main:
    web-application-type: reactive
  application:
    name: DEMO

logging:
  level:
#    org.springframework.data.r2dbc: DEBUG
    com.dimata.service.general.billing : DEBUG

server:
  port: 8032